version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./data:/var/lib/postgres
  node-app:
    build: ./ gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'